//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manga2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class mangacharacters
    {
        public int ID { get; set; }
        public Nullable<int> seriesID { get; set; }
        public string image { get; set; }
        [Required]
        public string bio { get; set; }
        public string strengths { get; set; }
        public string weaknesses { get; set; }
        [Required]
        public string Series { get; set; }
    
        public virtual mangaseries mangaseries { get; set; }
    }
}
